### ISSUE TITLE
I'm having some problems in running codes on the Camelyon16 dataset.

### ISSUE THREAD

**Issue by elephanttt** [sbelharbi/deep-wsl-histo-min-max-uncertainty#1]
Hi, I divided the patches from Cameyon16 dataset according to the CSV file in folds/ camelyon16-512-patch /split_0/fold_0/. And I also checked the input mask. But during the training process, the f1- on the training set was always nan. How to solve this problem?
![issue](https://user-images.githubusercontent.com/55304817/145138099-af803185-6fd9-4ada-affd-a64c753389e2.png)

**Comment by sbelharbi** [comment]
hi,
can you please check the target mask and predicted mask at 
https://github.com/sbelharbi/deep-wsl-histo-min-max-uncertainty/blob/29464285eabfa0914ff0bd79f2b6123c5dba7e1a/deepmil/train.py#L135

that they are correct and dont have nan. 
the target mask is used only to for tracking not train.

thanks

**Comment by elephanttt** [comment]
This is the training curves generated before, I don't know what went wrong.
![train](https://user-images.githubusercontent.com/55304817/145145718-5ef49b9b-260c-4906-ae16-764819e96fc5.png)

**Comment by elephanttt** [comment]
> hi, can you please check the target mask and predicted mask at
> 
> https://github.com/sbelharbi/deep-wsl-histo-min-max-uncertainty/blob/29464285eabfa0914ff0bd79f2b6123c5dba7e1a/deepmil/train.py#L135
> 
> that they are correct and dont have nan. the target mask is used only to for tracking not train.
> 
> thanks

When printing dice_back, I found nan in some of the values.
![nan](https://user-images.githubusercontent.com/55304817/145154803-88ad67f2-352c-4085-a753-6f3cc20b1d0b.PNG)

**Comment by elephanttt** [comment]
Sorry, I forget to set the args.use_reg and args.use_size_const to be True. 
Thanks a lot.  Your code is very useful ღ( ´･ᴗ･` )
