### ISSUE TITLE
Running Problem

### ISSUE THREAD

**Issue by jafarinia** [sbelharbi/deep-wsl-histo-min-max-uncertainty#5]
Hi.
Thank you for your open access wonderful article and everything.
I have a problem running your code.
It gives me this error:
File "/content/deep-wsl-histo-min-max-uncertainty/deepmil/train.py", line 29, in <module>
    from estimate_thres import EstimateThresSeg
ModuleNotFoundError: No module named 'estimate_thres'
As you can see the module "estimate_thres" is apparently non existent and based on name and everything it should be a python file written by you.
I'll be really grateful if you help me solve this issue.

**Comment by sbelharbi** [comment]
hi,
sorry about that.
the modules are for logging. you can ignore the error by commenting them.
i  fixed master branch.
thanks
